config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :pages, only: [] do
    collection do
      get :impressum
      get :contact
      get :privacy
      get :data_protection
    end
  end

  resources :friendships
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
# frozen_string_literal: true
class Bet < ApplicationRecord
  has_many :goals
  has_many :participants
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  STATUS_NEW_REQUEST = 0
  STATUS_ACCEPTED_REQUEST = 1
  STATUS_CANCELED_REQUEST = 2
end

app/models/goal.rb
# frozen_string_literal: true
class Goal < ApplicationRecord
  has_one :bet
end

app/models/participant.rb
# frozen_string_literal: true
class Participant < ApplicationRecord
  has_many :bets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @accepted_friendships = current_user.friendships.where(status_id: Friendship::STATUS_ACCEPTED_REQUEST) + current_user.inverse_friendships.where(status_id: Friendship::STATUS_ACCEPTED_REQUEST)
    @open_friendships = current_user.friendships.where(status_id: Friendship::STATUS_NEW_REQUEST)
    @unresponse_friendships = current_user.inverse_friendships.where(status_id: Friendship::STATUS_NEW_REQUEST)
    @friendship = Friendship.new
  end

  def create
    Friendship.create(friendship_params.merge({ user_id: current_user.id }))
    redirect_to friendships_path
  end

  def friendship_params
    params.require(:friendship).permit(:friend_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/friendships/index.haml
.panel.panel-default
  .panel-heading
    Neue Freundschaft hinzufügen
  .panel-body
    = form_for @friendship, html: { class: 'form-inline' } do |f|
      .form-group
        = f.label :friend_id
        = f.text_field :friend_id, class: 'form-control'
      .form-group
        = f.submit :save, class: 'btn btn-default'

%div
  / Nav tabs
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "accepted_friendships", "data-toggle" => "tab", :href => "#accepted_friendships", :role => "tab"} Freunde
    %li{:role => "presentation"}
      %a{"aria-controls" => "open_friendships", "data-toggle" => "tab", :href => "#open_friendships", :role => "tab"} Offene Anfragen
    %li{:role => "presentation"}
      %a{"aria-controls" => "unresponse_friendships", "data-toggle" => "tab", :href => "#unresponse_friendships", :role => "tab"} Unbeantwortet Anfragen
  / Tab panes
  .tab-content
    #accepted_friendships.tab-pane.active{:role => "tabpanel"}
      %table
        %tr
          %th
            email
          %th
            created_at
        - @accepted_friendships.each do |friendship|
          %tr
            %td
              = friendship.friend.email
            %td
              = friendship.created_at


    #open_friendships.tab-pane{:role => "tabpanel"}
      %table
        %tr
          %th
            email
          %th
            created_at
        - @open_friendships.each do |friendship|
          %tr
            %td
              = friendship.friend.email
            %td
              = friendship.created_at

    #unresponse_friendships.tab-pane{:role => "tabpanel"}
      %table
        %tr
          %th
            email
          %th
            created_at
        - @unresponse_friendships.each do |friendship|
          %tr
            %td
              = friendship.friend.email
            %td
              = friendship.created_at

app/views/layouts/_footer.haml
%footer.footer
  .container
    %p.text-center.text-muted
      %span.fa.fa-copyright
      dumme-wetten.de -
      = Date.today.year
    %p.text-center.text-muted
      = link_to 'Datenschutz', data_protection_pages_path
      |
      = link_to 'Impressum', impressum_pages_path
      |
      = link_to 'Geschäftsbedienungen', privacy_pages_path

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: 'button',
        data: { toggle: 'collapse', target: '#navbar' }}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse#navbar
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{href: '#', 'data-toggle' => 'dropdown', role: 'button', 'aria-expanded' => 'false', 'aria-haspopup' => "true"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to edit_user_registration_path do
                  %span.glyphicon.glyphicon-edit
                  Edit
              %li
                = link_to friendships_path do
                  %span.glyphicon.glyphicon-book
                  Freunde
              %li.divider
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %span.glyphicon.glyphicon-log-out
                  Logout
        - else
          %li
            = link_to 'Registrieren', new_user_registration_path
          %li
            = link_to 'Login', new_user_session_path

app/views/layouts/_navigation_links.haml
- if user_signed_in?
  %li
    = link_to 'Meine Wetten', ''
  %li
    = link_to 'Meine Freunde', ''
- else

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DummeWetten</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/data_protection.haml
Data Protection

app/views/pages/home.haml
.page-header
  %h1 Home